[project]
authors = ["TODO"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "dadrl"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
test = "python spqr_rl/scripts/test.py"
main-uavs = "python multiagent_rlrm/environments/cooperative_networkers_uavs/continuous/main_multiagent_cont.py"

[dependencies]
python = "3.11.*"
# wandb = ">=0.19.4,<0.20"

[pypi-dependencies]
dadrl = { path = ".", editable = true}
# opencv-python = ">=4.11.0.86, <5"
# imageio = ">=2.37.0, <3"
# torch = { version = ">=2.5.1", index = "https://download.pytorch.org/whl/cu124" }
# matplotlib = ">=3.10.0, <4"
# pandas = ">=2.2.3, <3"
# seaborn = ">=0.13.2, <0.14"
stable-baselines3 = ">=2.5.0, <3"

[activation]
env = { PYTHONPATH = ".:$PYTHONPATH"}
