defaults:
  - mappo_config
  - _self_



share_param_critic: True
clip_epsilon: 0.2
entropy_coef: 0.01      # 0 # low exploration
critic_coef: 1.          # 1. # weight of critic loss
loss_critic_type: "l2"
lmbda: 0.95               # 0.9 # GAE lambda   
scale_mapping: "biased_softplus_1.0" # "biased_softplus_1.0"
use_tanh_normal: False
minibatch_advantage: False 
